
name:budget Management action
on:
  push:
    branches: [ master, dev]
    paths: 'backend/budgetManagement/**'
  pull_request:
    branches: [ master, dev]
    paths: 'backend/budgetManagement/**'

jobs:

  sonar:
    runs-on: ubuntu-latest
    env:
      SONAR_PROJECT_KEY: DB1-budgetManagement
      SONAR_PROJECT_NAME: DB1-budgetManagement
      SONAR_HOST_URL:  https://sonarcloud.io
      SONAR_ORGANIZATION: zemoso-int
      WORKING_DIRECTORY: 'backend/budgetManagement/'
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('backend/budgetManagement/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: sonar
      run: mvn verify sonar:sonar -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} -Dsonar.projectName=${{ env.SONAR_PROJECT_NAME }} -Dsonar.organization=${{ env.SONAR_ORGANIZATION }} -Dsonar.host.url=${{ env.SONAR_HOST_URL }} -Dsonar.login=${{ secrets.SONAR_LOGIN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}

  docker:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    env:
      WORKING_DIRECTORY: 'backend/budgetManagement/'
      REGISTRY_GITHUB_LOGIN: 'https://docker.pkg.github.com'
    steps:
    - uses: actions/checkout@v2
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('backend/budgetManagement/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: extract branch name
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Build docker image
      run: docker build -t db1-budget:v1 .

    - name: Tag docker image
      env:
        DOCKER_TAG_BASE_URL:  "docker.pkg.github.com/zemoso-int/devops-bootcamp-1/db1-financial-tracker-budget-${{ steps.extract_branch.outputs.branch }}:${{ github.run_id }}"
      run: docker tag db1-budget:v1 ${{ env.DOCKER_TAG_BASE_URL }}

    - name: Login to github package repository
      run: echo ${{ secrets.REGISTRY_USER }} | docker login ${{ env.REGISTRY_GITHUB_LOGIN }} -u ${{ secrets.REGISTRY_USERNAME_TOKEN }} --password-stdin
       
    - name: Push image to github packages
      env:
        DOCKER_TAG_BASE_URL:  "docker.pkg.github.com/zemoso-int/devops-bootcamp-1/db1-financial-tracker-budget-${{ steps.extract_branch.outputs.branch }}:${{ github.run_id }}"
      run: docker push ${{ env.DOCKER_TAG_BASE_URL }}

    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
